# Generated by Django 5.2.8 on 2025-11-23 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_madre', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12)),
                ('fecha_nac_madre', models.DateField(blank=True, null=True)),
                ('edad_materna', models.IntegerField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=60, null=True)),
                ('cesfam', models.CharField(blank=True, max_length=80, null=True)),
                ('madre_vih', models.CharField(max_length=20)),
                ('vdrl_materno', models.CharField(max_length=30)),
                ('hepatitis_b_materno', models.CharField(max_length=30)),
                ('migrante', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('e_paridad', models.IntegerField(blank=True, null=True)),
                ('g_gestaciones', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_parto', models.CharField(max_length=40)),
                ('gases_cordon', models.BooleanField(default=False)),
                ('apego_canguro', models.BooleanField(default=False)),
                ('apego_tunel', models.BooleanField(default=False)),
                ('clampeo_tardio', models.BooleanField(default=False)),
                ('ive_causal_2', models.BooleanField(default=False)),
                ('destino_rn', models.CharField(max_length=40)),
                ('alojamiento_conjunto_puerperio', models.BooleanField(default=False)),
                ('lactancia_antes_60min', models.BooleanField(default=False)),
                ('acompanante_en_pabellon', models.CharField(blank=True, max_length=120, null=True)),
                ('observaciones_parto', models.TextField(blank=True, null=True)),
                ('interno', models.BooleanField(default=False)),
                ('resultado_examen_1', models.CharField(blank=True, max_length=40, null=True)),
                ('resultado_examen_2', models.CharField(blank=True, max_length=40, null=True)),
                ('tratamiento_parto', models.TextField(blank=True, null=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.madre')),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno_rn', models.CharField(max_length=80)),
                ('sexo', models.CharField(max_length=12)),
                ('peso', models.IntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('circunferencia_craneana', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('malformacion_congenita', models.BooleanField(default=False)),
                ('descripcion_malformacion', models.TextField(blank=True, null=True)),
                ('apgar_1min', models.IntegerField(blank=True, null=True)),
                ('apgar_5min', models.IntegerField(blank=True, null=True)),
                ('reanimacion_basica', models.BooleanField(default=False)),
                ('reanimacion_avanzada', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('profesional_que_vacuna_vhb', models.CharField(blank=True, max_length=120, null=True)),
                ('profilaxis_completa', models.BooleanField(default=False)),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True)),
                ('dias_gestacion', models.IntegerField(blank=True, null=True)),
                ('apego_inmediato', models.BooleanField(default=False)),
                ('destino_final', models.CharField(max_length=40)),
                ('notas_rn', models.TextField(blank=True, null=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.parto')),
            ],
        ),
    ]
