# Generated by Django 5.2.8 on 2025-11-23 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('cesfam', models.CharField(blank=True, max_length=100, null=True)),
                ('migrante', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('vih_positivo', models.BooleanField(default=False)),
                ('vdrl_resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('vdrl_tratamiento', models.BooleanField(default=False)),
                ('hepatitis_b_resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('profilaxis_completa', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateField()),
                ('hora_parto', models.TimeField(blank=True, null=True)),
                ('tipo_parto', models.CharField(max_length=50)),
                ('ive_causal2', models.BooleanField(default=False)),
                ('acompanante_pabellon', models.BooleanField(default=False)),
                ('clampeo_tardio', models.BooleanField(default=False)),
                ('gases_cordon', models.BooleanField(default=False)),
                ('apego_canguro', models.BooleanField(default=False)),
                ('apego_tunel', models.BooleanField(default=False)),
                ('profesional_responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('edad_gestacional_semanas', models.IntegerField(blank=True, null=True)),
                ('edad_gestacional_dias', models.IntegerField(blank=True, null=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.madre')),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('peso', models.IntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('circunferencia_craneana', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('malformacion_congenita', models.BooleanField(default=False)),
                ('descripcion_malformacion', models.TextField(blank=True, null=True)),
                ('apgar_1', models.IntegerField(blank=True, null=True)),
                ('apgar_5', models.IntegerField(blank=True, null=True)),
                ('reanimacion_basica', models.BooleanField(default=False)),
                ('reanimacion_avanzada', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('profesional_vacuna_vhb', models.CharField(blank=True, max_length=150, null=True)),
                ('profilaxis_completa', models.BooleanField(default=False)),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True)),
                ('dias_gestacion', models.IntegerField(blank=True, null=True)),
                ('apego_inmediato', models.BooleanField(default=False)),
                ('destino_final', models.CharField(max_length=50)),
                ('notas_rn', models.TextField(blank=True, null=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.parto')),
            ],
        ),
        migrations.CreateModel(
            name='VacunaBCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_madre', models.CharField(blank=True, max_length=150, null=True)),
                ('rut_madre', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento_madre', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento_hijo', models.DateField(blank=True, null=True)),
                ('sexo_rn', models.CharField(blank=True, max_length=10, null=True)),
                ('peso_rn', models.IntegerField(blank=True, null=True)),
                ('aplicada', models.BooleanField(default=False)),
                ('comuna', models.CharField(max_length=100)),
                ('reaccion_adversa', models.CharField(blank=True, max_length=100, null=True)),
                ('cama_ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('rn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formularios.reciennacido')),
            ],
        ),
    ]
