# Generated by Django 5.2.8 on 2025-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunabcg',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
