# Generated by Django 5.2.8 on 2025-11-23 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_vacunabcg_numero_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='comentario_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a supervisor'), ('APROBADO', 'Aprobado por supervisor'), ('RECHAZADO', 'Rechazado por supervisor')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='madre',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
