# Generated by Django 5.2.8 on 2025-11-23 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_madre_comentario_supervisor_madre_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madre',
            name='comentario_supervisor',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='madre',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='madre',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a Supervisor'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
    ]
