# Generated by Django 5.2.8 on 2025-11-24 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_remove_madre_comentario_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Supervisor'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='madre',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_parto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='circunferencia_craneana',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='destino_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
