# Generated by Django 5.2.8 on 2025-11-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_madre_estado_alter_madre_validado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='madre',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
