# Generated by Django 5.2.8 on 2025-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_madre_aprobado_madre_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='acompanante_corta_cordon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='acompanante_parto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='alumbramiento_rigido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='alumno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='causa_cesarea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='clasificacion_robson',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='estampado_placenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='induccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='manejo_dolor_farmacologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='motivo_no_acompanado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='persona_acompanante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='plan_parto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='recuerdos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='retira_placenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='ttc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='uso_sala_saip',
            field=models.BooleanField(default=False),
        ),
    ]
