# Generated by Django 5.2.8 on 2025-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_parto_acompanante_corta_cordon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunabcg',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
