# Generated by Django 5.2.8 on 2025-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_alter_vacunabcg_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
